/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codeforcessubmissiondownloader.app;

import com.codeforcessubmissiondownloader.operators.SubmissionFetcher;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Zahid
 */
public class CodeForcesSubmissionDownloader extends javax.swing.JFrame {

    /**
     *
     * Creates new form CodeForcesSubmissionDownloader
     */
    public static String path;
    public static String username;
    public static boolean isClosed;

    public CodeForcesSubmissionDownloader() {

        initComponents();
        isClosed = true;
        createUI();

    }

    private void createUI() {
        JPanel panel = new JPanel();
        JButton button = new JButton("Choose a File");
        final JLabel label = new JLabel();

        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                int option = fileChooser.showOpenDialog(getContentPane());
                if (option == JFileChooser.APPROVE_OPTION) {
                    File file = fileChooser.getSelectedFile();
                    label.setText("Folder Selected: " + file.getAbsolutePath());
                    path = file.getAbsolutePath();
                } else {
                    label.setText("Open command canceled");
                }
            }
        });

        panel.add(button);
        panel.add(label);
        panel.setBounds(50, 200, 700, 500);
        Font f = new Font("serif", Font.PLAIN, 12);
        label.setFont(f);
        getContentPane().add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Codeforces Submission Downloader");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 204, 51));
        setLocation(new java.awt.Point(250, 30));
        setMaximumSize(new java.awt.Dimension(850, 600));
        setMinimumSize(new java.awt.Dimension(850, 600));
        getContentPane().setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 200, 10, 10);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(250, 80, 250, 50);

        jLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel1.setText("Codeforces handle:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 60, 190, 80);

        jButton1.setText("Download");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 320, 170, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        username = jTextField1.getText();
        if (path == null) {

            JLabel errorMsg = new JLabel("Please Enter Correct Path");
            errorMsg.setFont(new Font("Sitka Small", Font.BOLD, 15));

            JOptionPane.showMessageDialog(rootPane, errorMsg, "Warning", JOptionPane.ERROR_MESSAGE);

        } else if (username.isBlank()) {

            JLabel errorMsg = new JLabel("handle can't be null");
            errorMsg.setFont(new Font("Sitka Small", Font.BOLD, 15));
            JOptionPane.showMessageDialog(rootPane, errorMsg, "Warning", JOptionPane.ERROR_MESSAGE);

        } else {

            JLabel msg = new JLabel("Downloading Please don't close the window,Please check the folder!!!!!");
            msg.setFont(new Font("Sitka Small", Font.BOLD, 15));
            JOptionPane.showMessageDialog(rootPane, msg, "Downloading", JOptionPane.INFORMATION_MESSAGE);

            SubmissionFetcher ob = new SubmissionFetcher();
            ob.start();
         

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodeForcesSubmissionDownloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodeForcesSubmissionDownloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodeForcesSubmissionDownloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodeForcesSubmissionDownloader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodeForcesSubmissionDownloader().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
